services:
  nginx:
    image: nginx:1.25.3
    ports:
      - "8030:80"
    volumes:
      - ./docker/files/nginx/etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/files/nginx/etc/nginx/conf.d/:/etc/nginx/conf.d/:ro
    command: ["nginx", "-g", "daemon off;"]
  api:
    image: terraform-slack-api
