// Code generated by go-swagger; DO NOT EDIT.

package channel

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewCloseChannelParams creates a new CloseChannelParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCloseChannelParams() *CloseChannelParams {
	return &CloseChannelParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCloseChannelParamsWithTimeout creates a new CloseChannelParams object
// with the ability to set a timeout on a request.
func NewCloseChannelParamsWithTimeout(timeout time.Duration) *CloseChannelParams {
	return &CloseChannelParams{
		timeout: timeout,
	}
}

// NewCloseChannelParamsWithContext creates a new CloseChannelParams object
// with the ability to set a context for a request.
func NewCloseChannelParamsWithContext(ctx context.Context) *CloseChannelParams {
	return &CloseChannelParams{
		Context: ctx,
	}
}

// NewCloseChannelParamsWithHTTPClient creates a new CloseChannelParams object
// with the ability to set a custom HTTPClient for a request.
func NewCloseChannelParamsWithHTTPClient(client *http.Client) *CloseChannelParams {
	return &CloseChannelParams{
		HTTPClient: client,
	}
}

/*
CloseChannelParams contains all the parameters to send to the API endpoint

	for the close channel operation.

	Typically these are written to a http.Request.
*/
type CloseChannelParams struct {

	/* ID.

	   channel id
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the close channel params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CloseChannelParams) WithDefaults() *CloseChannelParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the close channel params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CloseChannelParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the close channel params
func (o *CloseChannelParams) WithTimeout(timeout time.Duration) *CloseChannelParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the close channel params
func (o *CloseChannelParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the close channel params
func (o *CloseChannelParams) WithContext(ctx context.Context) *CloseChannelParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the close channel params
func (o *CloseChannelParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the close channel params
func (o *CloseChannelParams) WithHTTPClient(client *http.Client) *CloseChannelParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the close channel params
func (o *CloseChannelParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the close channel params
func (o *CloseChannelParams) WithID(id string) *CloseChannelParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the close channel params
func (o *CloseChannelParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *CloseChannelParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param id
	qrID := o.ID
	qID := qrID
	if qID != "" {

		if err := r.SetQueryParam("id", qID); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
