// Code generated by go-swagger; DO NOT EDIT.

package channel

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewFetchChannelParams creates a new FetchChannelParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewFetchChannelParams() *FetchChannelParams {
	return &FetchChannelParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewFetchChannelParamsWithTimeout creates a new FetchChannelParams object
// with the ability to set a timeout on a request.
func NewFetchChannelParamsWithTimeout(timeout time.Duration) *FetchChannelParams {
	return &FetchChannelParams{
		timeout: timeout,
	}
}

// NewFetchChannelParamsWithContext creates a new FetchChannelParams object
// with the ability to set a context for a request.
func NewFetchChannelParamsWithContext(ctx context.Context) *FetchChannelParams {
	return &FetchChannelParams{
		Context: ctx,
	}
}

// NewFetchChannelParamsWithHTTPClient creates a new FetchChannelParams object
// with the ability to set a custom HTTPClient for a request.
func NewFetchChannelParamsWithHTTPClient(client *http.Client) *FetchChannelParams {
	return &FetchChannelParams{
		HTTPClient: client,
	}
}

/*
FetchChannelParams contains all the parameters to send to the API endpoint

	for the fetch channel operation.

	Typically these are written to a http.Request.
*/
type FetchChannelParams struct {

	/* ID.

	   channel id
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the fetch channel params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *FetchChannelParams) WithDefaults() *FetchChannelParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the fetch channel params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *FetchChannelParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the fetch channel params
func (o *FetchChannelParams) WithTimeout(timeout time.Duration) *FetchChannelParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the fetch channel params
func (o *FetchChannelParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the fetch channel params
func (o *FetchChannelParams) WithContext(ctx context.Context) *FetchChannelParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the fetch channel params
func (o *FetchChannelParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the fetch channel params
func (o *FetchChannelParams) WithHTTPClient(client *http.Client) *FetchChannelParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the fetch channel params
func (o *FetchChannelParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the fetch channel params
func (o *FetchChannelParams) WithID(id string) *FetchChannelParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the fetch channel params
func (o *FetchChannelParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *FetchChannelParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param id
	qrID := o.ID
	qID := qrID
	if qID != "" {

		if err := r.SetQueryParam("id", qID); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
