// Code generated by go-swagger; DO NOT EDIT.

package channel

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewFetchChannelsParams creates a new FetchChannelsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewFetchChannelsParams() *FetchChannelsParams {
	return &FetchChannelsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewFetchChannelsParamsWithTimeout creates a new FetchChannelsParams object
// with the ability to set a timeout on a request.
func NewFetchChannelsParamsWithTimeout(timeout time.Duration) *FetchChannelsParams {
	return &FetchChannelsParams{
		timeout: timeout,
	}
}

// NewFetchChannelsParamsWithContext creates a new FetchChannelsParams object
// with the ability to set a context for a request.
func NewFetchChannelsParamsWithContext(ctx context.Context) *FetchChannelsParams {
	return &FetchChannelsParams{
		Context: ctx,
	}
}

// NewFetchChannelsParamsWithHTTPClient creates a new FetchChannelsParams object
// with the ability to set a custom HTTPClient for a request.
func NewFetchChannelsParamsWithHTTPClient(client *http.Client) *FetchChannelsParams {
	return &FetchChannelsParams{
		HTTPClient: client,
	}
}

/*
FetchChannelsParams contains all the parameters to send to the API endpoint

	for the fetch channels operation.

	Typically these are written to a http.Request.
*/
type FetchChannelsParams struct {

	/* TeamID.

	   encoded team id to list channels in, required if token belongs to org-wide app
	*/
	TeamID *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the fetch channels params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *FetchChannelsParams) WithDefaults() *FetchChannelsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the fetch channels params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *FetchChannelsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the fetch channels params
func (o *FetchChannelsParams) WithTimeout(timeout time.Duration) *FetchChannelsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the fetch channels params
func (o *FetchChannelsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the fetch channels params
func (o *FetchChannelsParams) WithContext(ctx context.Context) *FetchChannelsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the fetch channels params
func (o *FetchChannelsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the fetch channels params
func (o *FetchChannelsParams) WithHTTPClient(client *http.Client) *FetchChannelsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the fetch channels params
func (o *FetchChannelsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithTeamID adds the teamID to the fetch channels params
func (o *FetchChannelsParams) WithTeamID(teamID *string) *FetchChannelsParams {
	o.SetTeamID(teamID)
	return o
}

// SetTeamID adds the teamId to the fetch channels params
func (o *FetchChannelsParams) SetTeamID(teamID *string) {
	o.TeamID = teamID
}

// WriteToRequest writes these params to a swagger request
func (o *FetchChannelsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.TeamID != nil {

		// query param team_id
		var qrTeamID string

		if o.TeamID != nil {
			qrTeamID = *o.TeamID
		}
		qTeamID := qrTeamID
		if qTeamID != "" {

			if err := r.SetQueryParam("team_id", qTeamID); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
