// Code generated by go-swagger; DO NOT EDIT.

package channel

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewUpdateChannelParams creates a new UpdateChannelParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateChannelParams() *UpdateChannelParams {
	return &UpdateChannelParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateChannelParamsWithTimeout creates a new UpdateChannelParams object
// with the ability to set a timeout on a request.
func NewUpdateChannelParamsWithTimeout(timeout time.Duration) *UpdateChannelParams {
	return &UpdateChannelParams{
		timeout: timeout,
	}
}

// NewUpdateChannelParamsWithContext creates a new UpdateChannelParams object
// with the ability to set a context for a request.
func NewUpdateChannelParamsWithContext(ctx context.Context) *UpdateChannelParams {
	return &UpdateChannelParams{
		Context: ctx,
	}
}

// NewUpdateChannelParamsWithHTTPClient creates a new UpdateChannelParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateChannelParamsWithHTTPClient(client *http.Client) *UpdateChannelParams {
	return &UpdateChannelParams{
		HTTPClient: client,
	}
}

/*
UpdateChannelParams contains all the parameters to send to the API endpoint

	for the update channel operation.

	Typically these are written to a http.Request.
*/
type UpdateChannelParams struct {

	/* Channel.

	   channel spec
	*/
	Channel UpdateChannelBody

	/* ID.

	   channel id
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update channel params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateChannelParams) WithDefaults() *UpdateChannelParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update channel params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateChannelParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update channel params
func (o *UpdateChannelParams) WithTimeout(timeout time.Duration) *UpdateChannelParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update channel params
func (o *UpdateChannelParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update channel params
func (o *UpdateChannelParams) WithContext(ctx context.Context) *UpdateChannelParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update channel params
func (o *UpdateChannelParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update channel params
func (o *UpdateChannelParams) WithHTTPClient(client *http.Client) *UpdateChannelParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update channel params
func (o *UpdateChannelParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithChannel adds the channel to the update channel params
func (o *UpdateChannelParams) WithChannel(channel UpdateChannelBody) *UpdateChannelParams {
	o.SetChannel(channel)
	return o
}

// SetChannel adds the channel to the update channel params
func (o *UpdateChannelParams) SetChannel(channel UpdateChannelBody) {
	o.Channel = channel
}

// WithID adds the id to the update channel params
func (o *UpdateChannelParams) WithID(id string) *UpdateChannelParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the update channel params
func (o *UpdateChannelParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateChannelParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Channel); err != nil {
		return err
	}

	// query param id
	qrID := o.ID
	qID := qrID
	if qID != "" {

		if err := r.SetQueryParam("id", qID); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
