// Code generated by go-swagger; DO NOT EDIT.

package health

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/berquerant/terraform-slack/swagger/models"
)

// CheckAliveOKCode is the HTTP code returned for type CheckAliveOK
const CheckAliveOKCode int = 200

/*
CheckAliveOK Alive

swagger:response checkAliveOK
*/
type CheckAliveOK struct {

	/*
	  In: Body
	*/
	Payload *models.HealthModel `json:"body,omitempty"`
}

// NewCheckAliveOK creates CheckAliveOK with default headers values
func NewCheckAliveOK() *CheckAliveOK {

	return &CheckAliveOK{}
}

// WithPayload adds the payload to the check alive o k response
func (o *CheckAliveOK) WithPayload(payload *models.HealthModel) *CheckAliveOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the check alive o k response
func (o *CheckAliveOK) SetPayload(payload *models.HealthModel) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CheckAliveOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
