// Code generated by go-swagger; DO NOT EDIT.

package channel

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/berquerant/terraform-slack/swagger/models"
)

// FetchChannelHandlerFunc turns a function with the right signature into a fetch channel handler
type FetchChannelHandlerFunc func(FetchChannelParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn FetchChannelHandlerFunc) Handle(params FetchChannelParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// FetchChannelHandler interface for that can handle valid fetch channel params
type FetchChannelHandler interface {
	Handle(FetchChannelParams, *models.Principal) middleware.Responder
}

// NewFetchChannel creates a new http.Handler for the fetch channel operation
func NewFetchChannel(ctx *middleware.Context, handler FetchChannelHandler) *FetchChannel {
	return &FetchChannel{Context: ctx, Handler: handler}
}

/*
	FetchChannel swagger:route GET /channel channel fetchChannel

Fetch a channel
*/
type FetchChannel struct {
	Context *middleware.Context
	Handler FetchChannelHandler
}

func (o *FetchChannel) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewFetchChannelParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
