// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Slack API for Terraform provider
//
//	Schemes:
//	  http
//	Host: 127.0.0.1:8030
//	BasePath: /v0
//	Version: 0.1.0
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
